"""empty message

Revision ID: 23aadffbc7e0
Revises: cdc9a6220746
Create Date: 2024-12-05 08:39:38.608901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '23aadffbc7e0'
down_revision: Union[str, None] = 'cdc9a6220746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rollo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Tipo_Producto', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('Material_1', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('Material_2', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('Material_3', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('unidades_Ancho', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('Unidades_Calibre', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('Unidades_Largo', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('Peso_Estructura', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('Tipo_Bobinado', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('Numero_Bobinado', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('Peso_Rollo', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('Fulle_Izquierdo', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('Fuelle_Derecho', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('Acabado', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('Tratado', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.alter_column('Color',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('UnidadesLargo')
        batch_op.drop_column('PesoPorRollo')
        batch_op.drop_column('UnidadesCalibre')
        batch_op.drop_column('Material')
        batch_op.drop_column('unidadesAncho')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rollo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidadesAncho', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('Material', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('UnidadesCalibre', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('PesoPorRollo', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('UnidadesLargo', sa.VARCHAR(), nullable=False))
        batch_op.alter_column('Color',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('Tratado')
        batch_op.drop_column('Acabado')
        batch_op.drop_column('Fuelle_Derecho')
        batch_op.drop_column('Fulle_Izquierdo')
        batch_op.drop_column('Peso_Rollo')
        batch_op.drop_column('Numero_Bobinado')
        batch_op.drop_column('Tipo_Bobinado')
        batch_op.drop_column('Peso_Estructura')
        batch_op.drop_column('Unidades_Largo')
        batch_op.drop_column('Unidades_Calibre')
        batch_op.drop_column('unidades_Ancho')
        batch_op.drop_column('Material_3')
        batch_op.drop_column('Material_2')
        batch_op.drop_column('Material_1')
        batch_op.drop_column('Tipo_Producto')

    # ### end Alembic commands ###
