"""empty message

Revision ID: 2a6cf52e9d5d
Revises: 3f156991f3e2
Create Date: 2025-01-03 07:55:54.272004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2a6cf52e9d5d'
down_revision: Union[str, None] = '3f156991f3e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rollo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Referencia_Provispol', sqlmodel.sql.sqltypes.AutoString(), server_default='DEFAULT_VALUE', nullable=False))
    
    # Eliminar el valor predeterminado después de la creación
    with op.batch_alter_table('rollo', schema=None) as batch_op:
        batch_op.alter_column('Referencia_Provispol', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rollo', schema=None) as batch_op:
        batch_op.drop_column('Referencia_Provispol')

    # ### end Alembic commands ###
