"""empty message

Revision ID: 3f156991f3e2
Revises: 23aadffbc7e0
Create Date: 2024-12-05 19:53:02.517801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3f156991f3e2'
down_revision: Union[str, None] = '23aadffbc7e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rollo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Unidades_Ancho', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('estado_eliminado', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.drop_column('unidades_Ancho')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rollo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidades_Ancho', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('estado_eliminado')
        batch_op.drop_column('Unidades_Ancho')

    # ### end Alembic commands ###
