"""empty message

Revision ID: 92c7c8c66cdd
Revises: 
Create Date: 2024-11-13 11:56:37.286618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '92c7c8c66cdd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rollo',
    sa.Column('Ancho', sa.Integer(), nullable=False),
    sa.Column('Calibre', sa.Integer(), nullable=False),
    sa.Column('Color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Grupo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Largo', sa.Integer(), nullable=False),
    sa.Column('Material', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('PesoPorRollo', sa.Integer(), nullable=False),
    sa.Column('UnidadesCalibre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('UnidadesLargo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unidadesAncho', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Codigo_Siigo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('Codigo_Siigo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rollo')
    # ### end Alembic commands ###
