"""empty message

Revision ID: cdc9a6220746
Revises: 92c7c8c66cdd
Create Date: 2024-11-13 16:57:53.499370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cdc9a6220746'
down_revision: Union[str, None] = '92c7c8c66cdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rollo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sqlmodel.sql.sqltypes.AutoString(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rollo', schema=None) as batch_op:
        batch_op.drop_column('fecha')

    # ### end Alembic commands ###
