"""empty message

Revision ID: d0e93d8b6717
Revises: 
Create Date: 2025-01-27 21:58:25.868512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd0e93d8b6717'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rollo',
    sa.Column('Tipo_Producto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Grupo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Material_1', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Material_2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Material_3', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Ancho', sa.Integer(), nullable=False),
    sa.Column('Unidades_Ancho', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Calibre', sa.Integer(), nullable=False),
    sa.Column('Unidades_Calibre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Largo', sa.Integer(), nullable=False),
    sa.Column('Unidades_Largo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Peso_Estructura', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Tipo_Bobinado', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Numero_Bobinado', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Peso_Rollo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Fulle_Izquierdo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Fuelle_Derecho', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Acabado', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Tratado', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Referencia', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Referencia_Provispol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Codigo_Siigo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estado_eliminado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('Codigo_Siigo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rollo')
    # ### end Alembic commands ###
